timezone: America/New_York
markdown: redcarpet
paginate: 5
permalink: pretty
excerpt_separator: <span id="more"></span>
exclude:
  - src
  - node_modules
  - bower_components
  - Gruntfile.js
  - bower.json
  - package.json
  - README.md
  - CNAME
  - Gemfile
  - Procfile
name: Mike Raimondi
description: Mike Raimondi's personal site
url: http://www.mikeraimondi.com
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      comments: true

redcarpet:
  extensions: ['smart']
